# Generated by Django 5.2.4 on 2025-07-31 01:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(choices=[("top", "Top"), ("middle", "Middle"), ("base", "Base")], max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Daily", "데일리"),
                            ("Special", "특별한 날"),
                            ("Relax", "휴식 및 기분전환"),
                            ("Outdoor", "운동 및 야외 활동"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
                ("product_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=50)),
                ("release_year", models.IntegerField()),
                (
                    "intensity",
                    models.CharField(
                        choices=[("light", "Light"), ("medium", "Medium"), ("strong", "Strong")], max_length=10
                    ),
                ),
                (
                    "base_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "base"}, related_name="base_perfumes", to="product.note"
                    ),
                ),
                ("main_accords", models.ManyToManyField(related_name="perfumes", to="product.accord")),
                (
                    "middle_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "middle"}, related_name="middle_perfumes", to="product.note"
                    ),
                ),
                (
                    "top_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "top"}, related_name="top_perfumes", to="product.note"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_histories",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
