# Generated by Django 5.2.2 on 2025-07-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
