# Generated by Django 5.2.2 on 2025-07-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_product_img_url"),
        ("product", "0002_alter_product_product_img_url_perfume"),
    ]

    operations = []
