# Generated by Django 5.2.4 on 2025-07-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_usagehistory_user"),
        ("product", "0003_alter_usagehistory_user_like"),
    ]

    operations = []
