# Generated by Django 5.2.4 on 2025-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_merge_20250731_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfume",
            name="category",
            field=models.CharField(
                choices=[
                    ("parfum", "퍼퓸"),
                    ("eau_de_parfum", "오드 퍼퓸"),
                    ("eau_de_toilette", "오드 뚜왈렛"),
                    ("eau_de_cologne", "오드 코롱"),
                    ("eau_fraiche", "오 프레쉬"),
                ],
                default="eau_de_parfum",
                max_length=20,
            ),
        ),
    ]
