# Generated by Django 5.2.4 on 2025-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_merge_20250731_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
