# Generated by Django 5.2.4 on 2025-08-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_perfume_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfume",
            old_name="category",
            new_name="concentration",
        ),
    ]
