# Generated by Django 5.2.4 on 2025-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_category_perfume_concentration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfume",
            name="concentration",
        ),
        migrations.AlterField(
            model_name="perfume",
            name="intensity",
            field=models.CharField(
                choices=[
                    ("parfum", "퍼퓸"),
                    ("eau_de_parfum", "오드 퍼퓸"),
                    ("eau_de_toilette", "오드 뚜왈렛"),
                    ("eau_de_cologne", "오드 코롱"),
                    ("eau_fraiche", "오 프레쉬"),
                ],
                default="eau_de_parfum",
                max_length=20,
            ),
        ),
    ]
