# Generated by Django 5.2.4 on 2025-08-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_perfume_concentration_alter_perfume_intensity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="perfume",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="product.perfume",
            ),
        ),
    ]
