# Generated by Django 5.2.4 on 2025-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_perfume"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
