# Generated by Django 5.2.4 on 2025-08-08 05:58

import django.db.models.deletion
from django.db import migrations, models


def assign_default_perfume_to_null_products(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    Perfume = apps.get_model("product", "Perfume")

    default_perfume, _ = Perfume.objects.get_or_create(
        name="기본향수",
        brand="DefaultBrand",
        release_year=2025,
        intensity="eau_de_parfum",
    )
    Product.objects.filter(perfume__isnull=True).update(perfume=default_perfume)


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_views_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="volume_ml",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(assign_default_perfume_to_null_products),
        migrations.AlterField(
            model_name="product",
            name="perfume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="product.perfume"
            ),
        ),
    ]
