# Generated by Django 5.2.4 on 2025-08-08 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_views_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainAccord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="perfume",
            name="users",
            field=models.ManyToManyField(related_name="perfumes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="main_accords",
            field=models.ManyToManyField(related_name="perfumes", to="product.mainaccord"),
        ),
    ]
