# Generated by Django 5.2.4 on 2025-08-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_mainaccord_perfume_users_alter_perfume_main_accords"),
        ("product", "0010_remove_product_brand_product_volume_ml_and_more"),
    ]

    operations = []
