# Generated by Django 5.2.4 on 2025-08-12 15:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_merge_20250808_1648"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeReturnRequest",
            fields=[
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(choices=[("exchange", "교환"), ("return", "반품")], max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리중"),
                            ("completed", "승인 완료"),
                            ("rejected", "승인거절"),
                        ],
                        max_length=100,
                    ),
                ),
                ("requests_at", models.CharField(blank=True, max_length=100, null=True)),
                ("exchange_return", models.CharField(blank=True, max_length=100, null=True)),
                ("requests_reason", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product_Exchange",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_img_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exchanges", to="product.product"
                    ),
                ),
            ],
        ),
    ]
