# Generated by Django 5.2.4 on 2025-08-11 14:33

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension, VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_merge_20250808_1648"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="perfume",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
