# Generated by Django 5.2.4 on 2025-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_exchangereturnrequest_product_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="is_exchange_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="is_return_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("processing", "처리중"),
                    ("completed", "승인 완료"),
                    ("rejected", "승인 거절"),
                ],
                max_length=100,
            ),
        ),
    ]
