# Generated by Django 5.2.4 on 2025-08-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_exchangereturnrequest_is_exchange_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="requests_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("processing", "처리중"),
                    ("completed", "승인 완료"),
                    ("rejected", "승인 거절"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="type",
            field=models.CharField(choices=[("exchange", "교환"), ("return", "반품")], max_length=20),
        ),
    ]
