# Generated by Django 5.2.4 on 2025-08-13 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_exchangereturnrequest_requests_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="requests_at",
        ),
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="exchange_return",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="product.product_exchange"
            ),
        ),
    ]
