# Generated by Django 5.2.4 on 2025-08-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_perfume_embedding"),
        ("product", "0015_remove_exchangereturnrequest_order_id_and_more"),
    ]

    operations = []
