# Generated by Django 5.2.5 on 2025-08-13 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_merge_20250813_1704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="is_exchange_available",
        ),
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="is_return_available",
        ),
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="exchangereturnrequest",
            name="requested_at",
        ),
        migrations.RemoveField(
            model_name="product_exchange",
            name="product_img_url",
        ),
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exchangereturnrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product_exchange",
            name="is_exchange_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product_exchange",
            name="is_return_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="exchange_return",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="product.product_exchange",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="requests_reason",
            field=models.TextField(default="exit"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="type",
            field=models.CharField(choices=[("exchange", "Exchange"), ("return", "Return")], max_length=10),
        ),
    ]
