# Generated by Django 5.2.5 on 2025-08-14 01:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_remove_exchangereturnrequest_is_exchange_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductExchange",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_exchange_available", models.BooleanField(default=True)),
                ("is_return_available", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exchanges", to="product.product"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="exchangereturnrequest",
            name="exchange_return",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="product.productexchange"
            ),
        ),
        migrations.DeleteModel(
            name="Product_Exchange",
        ),
    ]
