services:
  django:
    container_name: django
    env_file:
      - .local.env/.local..local.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    build:
      context: .
    working_dir: /yours_scently
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             poetry run python manage.py runserver 0.0.0.0:8000
             "
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/yours_scently/apps/static
      - media_volume:/yours_scently/apps/media
      - ./:/yours_scently/
    networks:
      - ws
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./resources/nginx/local.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/yours_scently/app/static
      - media_volume:/yours_scently/app/media
    networks:
      - ws

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw1234
      POSTGRES_ROOT_USER: postgres
      POSTGRES_DB: yours_scently_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ws
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  ws:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
