# Generated by Django 5.2.4 on 2025-07-31 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("similarity_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("type", models.CharField(choices=[("ai", "AI 기반"), ("survey", "설문 기반")], max_length=10)),
                ("context", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("perfume", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.perfume")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "recommendation",
            },
        ),
    ]
