# Generated by Django 5.2.4 on 2025-07-31 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0004_merge_20250731_1537"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("ai", "AI 기반"), ("survey", "설문 기반")], max_length=10)),
                ("context", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("similarity_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_histories",
                        to="product.perfume",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="recommendation.recommendation",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
