# Generated by Django 5.2.4 on 2025-07-31 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_merge_20250730_1725"),
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "perfume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_histories",
                        to="product.perfume",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="recommendation.recommendation",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
