# Generated by Django 5.2.4 on 2025-08-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
