# Generated by Django 5.2.4 on 2025-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0002_recommendation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
