events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 30M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_vary on;

    upstream django_server {
        server django:8000;
    }

    # HTTP to HTTPS 리디렉션
    server {
        listen 80;
        server_name yours-scently.store www.yours-scently.store;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS 서버
    server {
        listen 443 ssl;
        server_name yours-scently.store www.yours-scently.store;

        ssl_certificate /etc/letsencrypt/live/yours-scently.store/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yours-scently.store/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' "$http_origin" always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-CSRFToken' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' text/plain;
                return 204;
            }

            proxy_pass http://django_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
        }

        location /static/ {
            alias /yours_scently/app/static/;
            autoindex off;
            expires 1d;
            access_log off;
        }

        location /media/ {
            alias /yours_scently/app/media/;
            autoindex off;
            expires 1d;
            access_log off;
        }
    }
}