# Generated by Django 5.2.4 on 2025-07-31 01:45

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models.withdrawal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                (
                    "gender",
                    models.CharField(choices=[("MALE", "남성"), ("FEMALE", "여성")], default="MALE", max_length=6),
                ),
                ("birth_date", models.DateField(default=datetime.date(2000, 1, 1))),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "관리자"), ("GENERAL", "일반회원")], default="GENERAL", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="FragrancePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("parfum", "Parfum (20~30%, 8~12시간)"),
                            ("eau_de_parfum", "Eau de Parfum (15~20%, 6~8시간)"),
                            ("eau_de_toilette", "Eau de Toilette (5~15%, 4~6시간)"),
                            ("eau_de_cologne", "Eau de Cologne (2~5%, 2~4시간)"),
                            ("eau_fraiche", "Eau Fraîche (1~3%, 1~2시간)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preferred_accords", models.ManyToManyField(related_name="preferred_accords", to="product.accord")),
                (
                    "preferred_base_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "base"}, related_name="preferred_base_notes", to="product.note"
                    ),
                ),
                (
                    "preferred_middle_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "middle"}, related_name="preferred_middle_notes", to="product.note"
                    ),
                ),
                (
                    "preferred_top_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "top"}, related_name="preferred_top_notes", to="product.note"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragrance_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=100)),
                ("result_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NOT_ACCURATE", "추천이 정확하지 않음"),
                            ("NOT_SATISFIED", "불만족"),
                            ("ETC", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_detail", models.TextField()),
                ("due_date", models.DateField(default=apps.users.models.withdrawal.default_due_date)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("KAKAO", "카카오"), ("NAVER", "네이버")], max_length=10)),
                ("provider_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
                "unique_together": {("provider", "provider_id")},
            },
        ),
    ]
