# Generated by Django 5.2.4 on 2025-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("MALE", "남성"), ("FEMALE", "여성")], default="MALE", max_length=6),
        ),
    ]
