# Generated by Django 5.2.4 on 2025-07-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_socialuser"),
        ("users", "0003_user_gender"),
    ]

    operations = []
