# Generated by Django 5.2.2 on 2025-07-28 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_accord_note_perfume"),
    ]

    operations = [
        migrations.CreateModel(
            name="FragrancePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("parfum", "Parfum (20~30%, 8~12시간)"),
                            ("eau_de_parfum", "Eau de Parfum (15~20%, 6~8시간)"),
                            ("eau_de_toilette", "Eau de Toilette (5~15%, 4~6시간)"),
                            ("eau_de_cologne", "Eau de Cologne (2~5%, 2~4시간)"),
                            ("eau_fraiche", "Eau Fraîche (1~3%, 1~2시간)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferences", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preferred_accords", models.ManyToManyField(related_name="preferred_accords", to="users.accord")),
                (
                    "preferred_base_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "base"}, related_name="preferred_base_notes", to="users.note"
                    ),
                ),
                (
                    "preferred_middle_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "middle"}, related_name="preferred_middle_notes", to="users.note"
                    ),
                ),
                (
                    "preferred_top_notes",
                    models.ManyToManyField(
                        limit_choices_to={"type": "top"}, related_name="preferred_top_notes", to="users.note"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragrance_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
