# Generated by Django 5.2.2 on 2025-07-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_is_active"),
        ("users", "0006_fragrancepreference"),
    ]

    operations = []
