# Generated by Django 5.2.4 on 2025-07-29 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models.withdrawal


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_merge_20250729_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NOT_ACCURATE", "추천이 정확하지 않음"),
                            ("NOT_SATISFIED", "불만족"),
                            ("ETC", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_detail", models.TextField()),
                ("due_date", models.DateField(default=apps.users.models.withdrawal.default_due_date)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
    ]
