# Generated by Django 5.2.4 on 2025-07-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_withdrawal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Perfume",
        ),
    ]
